pollWebsite/poll/urls.py
from django.urls import path
from . import views

app_name = 'poll'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('<int:pk>/', views.DetailView.as_view(), name="details"),
    path('<int:pk>/results/', views.ResultsView.as_view(), name="results"),
    path('<int:question_id>/vote/', views.vote, name="vote"),
]

pollWebsite/pollWebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('poll.urls')),
]

pollWebsite/poll/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=255)
    pub_date = models.DateTimeField("date published")

    class Meta:
        ordering = ['-pub_date', 'question_text'] 

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return timezone.now()-datetime.timedelta(days=1) <= self.pub_date <= timezone.now()


class Choice(models.Model):
    question = models.ForeignKey('Question', on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

pollWebsite/poll/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Question, Choice

# Create your views here.
class IndexView(generic.ListView):
    model = Question
    paginate_by = 5
    template_name = 'poll/index.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')

class DetailView(generic.DetailView):
    model = Question
    template_name = 'poll/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())
        
class ResultsView(generic.DetailView):
    model = Question
    template_name = 'poll/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'poll/detail.html', {
            'question': question,
            'error_message':"You didn't select a choice."
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('poll:results', args=(question.id,)))

pollWebsite/poll/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" rel="stylesheet"></link>
        <meta charset="utf-8">
        {% block title %}<title>Local Library</title>{% endblock %}

        {% load static %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2">
                    {% block sidebar %}
                        <ul class="sidebar-nav">
                            <li><a href="{% url 'poll:index' %}">Home</a></li>
                        </ul>
                    {% endblock %}
                </div>
    
                <div class="col-sm-10 ">
                    {% block content %}
                    {% endblock %}
    
                    {% block pagination %}
                        {% if is_paginated %}
                            <div class="pagination">
                                <span class="page-links">
                                    {% if page_obj.has_previous %}
                                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Previous</a>
                                    {% endif %}
                                        <span class="page-current">
                                            <p>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</p>
                                        </span>
                                    {% if page_obj.has_next %}
                                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Next</a>
                                    {% endif %}
                                </span>
                            </div>
                        {% endif %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

pollWebsite/poll/templates/poll/detail.html
{% extends 'base.html' %}

{% block content %}

    <form method="post" action="{% url 'poll:vote' question.id %}">
        {% csrf_token %}
        <fieldset>
            <legend>{{ question.question_text }}</legend>
            {% if error_message %}
                <p>{{ error_message }}</p>
            {% endif %}

            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" value="{{ choice.id }}" id="{{ forloop.counter }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
    </form>
    
{% endblock %}

pollWebsite/poll/templates/poll/index.html
{% extends 'base.html' %}

{% block title %}<title>Question List</title>{% endblock %}

{% block content %}

    <h1>Question List</h1>

    {% if question_list %}
        <ul>
            {% for question in question_list %}
                <li><a href="{% url 'poll:details' question.id %}">Question {{ question.id }}</a>: {{ question.question_text }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}

{% endblock %}

pollWebsite/poll/templates/poll/results.html
{% extends 'base.html' %}

{% block content %}

    <h1>{{ question.question_text }}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ forloop.counter }}: {{ choice.choice_text }} -- vote {{ choice.votes }}</li>
        {% endfor %}
    </ul>

{% endblock %}